import {Category} from './catalog.interface';

export const mainCategories: Category[] = [
  {
    id: 1,
    name: 'Меблі',
    routerLink: 'furniture',
    showSubcategories: false,
    subcategories: [
      {
        id: 11,
        name: 'Столи',
        routerLink: 'tables',
        products: [
          {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          }
        ]
      },
      {
        id: 12,
        name: 'Пуфи',
        routerLink: 'ottomans',
        products: [
          {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 13,
        name: 'Стільці',
        routerLink: 'chairs',
        products: [
          {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 14,
        name: 'Крісла',
        routerLink: 'armchairs',
        products: [
          {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 15,
        name: 'Ліжка',
        routerLink: 'beds',
        products: [
          {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 16,
        name: 'Дивани',
        routerLink: 'sofas',
        products: [
          {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 17,
        name: 'Стелажі',
        routerLink: 'shelves',
        products: [
          {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 18,
        name: 'Тумби',
        routerLink: 'nightstands',
        products: [
          {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 19,
        name: 'Комоди',
        routerLink: 'dressers',
        products: [
          {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }, {
            name: 'Кавовий столик',
            descr: 'Виробник: Франція',
            shortDescr: 'Модель: 06-00486',
            price: 6500,
            image: '',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      }
    ]
  },
  {
    id: 2,
    name: 'Освітлення',
    routerLink: 'lighting',
    showSubcategories: false,
    subcategories: [
      {id: 21, name: 'Люстри', routerLink: 'chandeliers'},
      {id: 22, name: 'Лампи', routerLink: 'lamps'}
    ]
  },
  {
    id: 3,
    name: 'Сантехніка',
    routerLink: 'plumbing',
    showSubcategories: false,
    subcategories: [
      {id: 31, name: 'Ванни', routerLink: 'bathtubs'},
      {id: 32, name: 'Душі', routerLink: 'showers'}
    ]
  },
  {
    id: 4,
    name: 'Аксесуари',
    routerLink: 'accessories',
    showSubcategories: false,
    subcategories: [
      {id: 41, name: 'Подушки', routerLink: 'cushions'},
      {id: 42, name: 'Килими', routerLink: 'rugs'}
    ]
  },
  {
    id: 5,
    name: 'Інше',
    routerLink: 'other',
    showSubcategories: false,
    subcategories: [
      {id: 51, name: 'Декор', routerLink: 'decor'},
      {id: 52, name: 'Посуд', routerLink: 'tableware'}
    ]
  }
];
