import {Category} from './catalog.interface';

export const mainCategories: Category[] = [
  {
    id: 1,
    name: 'Меблі',
    routerLink: 'furniture',
    showSubcategories: false,
    subcategories: [
      {
        id: 11,
        name: 'Столи',
        routerLink: 'tables',
        products: [
          {
            id: 111,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2
          },
          {
            id: 112,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 113,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          },
          {
            id: 114,
            name: 'Крісло Lambrusco',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          },
          {
            id: 115,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 116,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 117,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          },
          {
            id: 118,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          }
        ]
      },
      {
        id: 12,
        name: 'Пуфи',
        routerLink: 'ottomans',
        products: [
          {
            id: 121,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 122,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 123,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 124,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 125,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 126,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]

      },
      {
        id: 13,
        name: 'Стільці',
        routerLink: 'chairs',
        products: [
          {
            id: 131,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 132,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 133,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 134,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 135,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 136,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 14,
        name: 'Крісла',
        routerLink: 'armchairs',
        products: [
          {
            id: 141,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 142,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 143,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 144,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 145,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 146,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 15,
        name: 'Ліжка',
        routerLink: 'beds',
        products: [
          {
            id: 151,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 152,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 153,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 154,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 155,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 156,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 16,
        name: 'Дивани',
        routerLink: 'sofas',
        products: [
          {
            id: 161,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 162,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 163,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 164,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 165,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 166,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 17,
        name: 'Стелажі',
        routerLink: 'shelves',
        products: [
          {
            id: 171,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 172,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 173,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 174,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 175,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 176,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 18,
        name: 'Тумби',
        routerLink: 'nightstands',
        products: [
          {
            id: 181,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 182,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 183,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 184,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 185,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 186,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 19,
        name: 'Комоди',
        routerLink: 'dressers',
        products: [
          {
            id: 191,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 192,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 193,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 194,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 195,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 196,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      }
    ]
  },
  {
    id: 2,
    name: 'Освітлення',
    routerLink: 'lighting',
    showSubcategories: false,
    subcategories: [
      {id: 21, name: 'Люстри', routerLink: 'chandeliers'},
      {id: 22, name: 'Лампи', routerLink: 'lamps'}
    ]
  },
  {
    id: 3,
    name: 'Сантехніка',
    routerLink: 'plumbing',
    showSubcategories: false,
    subcategories: [
      {id: 31, name: 'Ванни', routerLink: 'bathtubs'},
      {id: 32, name: 'Душі', routerLink: 'showers'}
    ]
  },
  {
    id: 4,
    name: 'Аксесуари',
    routerLink: 'accessories',
    showSubcategories: false,
    subcategories: [
      {id: 41, name: 'Подушки', routerLink: 'cushions'},
      {id: 42, name: 'Килими', routerLink: 'rugs'}
    ]
  },
  {
    id: 5,
    name: 'Інше',
    routerLink: 'other',
    showSubcategories: false,
    subcategories: [
      {
        id: 51,
        name: 'Декор',
        routerLink: 'decor',
        products: [
          {
            id: 511,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 512,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 513,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          }
        ]
      },
      {
        id: 52,
        name: 'Посуд',
        routerLink: 'tableware',
        products: [
          {
            id: 521,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
          },
          {
            id: 522,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          },
          {
            id: 523,
            name: 'Кавовий столик',
            descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
            shortDescr: '06-00486',
            price: 6500,
            image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
            brand: 'Франція',
            category: 'string',
            instock: true,
            countInStock: 2,
            raiting: 2,
            numReviews: 2,
            sale: true
          }
        ]
      }
    ]
  },
  {
    id: 6,
    name: 'Новинки',
    routerLink: 'new',
    showSubcategories: false,
    products: [
      {
        id: 661,
        name: 'Кавовий столик',
        descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
        shortDescr: '06-00486',
        price: 6500,
        image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
        brand: 'Франція',
        category: 'string',
        instock: true,
        countInStock: 2,
        raiting: 2,
        numReviews: 2,
      },
      {
        id: 662,
        name: 'Кавовий столик',
        descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
        shortDescr: '06-00486',
        price: 6500,
        image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
        brand: 'Франція',
        category: 'string',
        instock: true,
        countInStock: 2,
        raiting: 2,
        numReviews: 2,
      },
      {
        id: 663,
        name: 'Кавовий столик',
        descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
        shortDescr: '06-00486',
        price: 6500,
        image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
        brand: 'Франція',
        category: 'string',
        instock: true,
        countInStock: 2,
        raiting: 2,
        numReviews: 2,
      }
    ]
  },
  {
    id: 7,
    name: 'Популярне',
    routerLink: 'popular',
    showSubcategories: false,
    products: [
      {
        id: 771,
        name: 'Кавовий столик',
        descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
        shortDescr: '06-00486',
        price: 6500,
        image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
        brand: 'Франція',
        category: 'string',
        instock: true,
        countInStock: 2,
        raiting: 2,
        numReviews: 2,
      },
      {
        id: 772,
        name: 'Кавовий столик',
        descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
        shortDescr: '06-00486',
        price: 6500,
        image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
        brand: 'Франція',
        category: 'string',
        instock: true,
        countInStock: 2,
        raiting: 2,
        numReviews: 2,
        sale: true
      },
      {
        id: 773,
        name: 'Кавовий столик',
        descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
        shortDescr: '06-00486',
        price: 6500,
        image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
        brand: 'Франція',
        category: 'string',
        instock: true,
        countInStock: 2,
        raiting: 2,
        numReviews: 2,
        sale: true
      }
    ]
  },
  {
    id: 8,
    name: 'Акції',
    routerLink: 'shares',
    showSubcategories: false,
    products: [
      {
        id: 881,
        name: 'Кавовий столик',
        descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
        shortDescr: '06-00486',
        price: 6500,
        image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
        brand: 'Франція',
        category: 'string',
        instock: true,
        countInStock: 2,
        raiting: 2,
        numReviews: 2,
        sale: true
      },
      {
        id: 882,
        name: 'Кавовий столик',
        descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
        shortDescr: '06-00486',
        price: 6500,
        image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
        brand: 'Франція',
        category: 'string',
        instock: true,
        countInStock: 2,
        raiting: 2,
        numReviews: 2,
        sale: true
      },
      {
        id: 883,
        name: 'Кавовий столик',
        descr: "Запрошуємо до світу затишку та комфорту з нашим кріслом. Його елегантний дизайн поєднується з м'якими подушками, створюючи ідеальне місце для відпочинку. Високоякісний матеріал та дбайливо продумані деталі роблять це крісло вишуканим додатком для вашого простору. Розкривайте в ньому нові рівні комфорту та насолоди.",
        shortDescr: '06-00486',
        price: 6500,
        image: 'https://almode.ru/uploads/posts/2022-12/1671466927_1-almode-ru-p-servirovka-novogodnego-stola-s-beloi-posud-1.jpg',
        brand: 'Франція',
        category: 'string',
        instock: true,
        countInStock: 2,
        raiting: 2,
        numReviews: 2,
        sale: true
      }
    ]
  }
];
