const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INSUFFICIENT_STOCK: 422,
  INTERNAL_SERVER_ERROR: 500,
};

const MESSAGES = {
  MISSING_REQUIRED_FIELDS: 'Missing required fields.',
  EMPTY_QUERY_ERROR: 'Your query have a nullable length.',
  ORDER_NOT_FOUND: 'Order was not found.',
  PRODUCT_NOT_FOUND: 'Product not found.',
  VALIDATION_ERROR: 'Some errors was occured when validate.',
  DATABASE_ERROR: 'Some error occurred on DB.',
  INVALID_CREDENTIALS: 'Wrong email or password.',
  NEW_USER_CREATED: 'New user created.',
  GOOGLE_FETCH_FAILURE: 'Failed to fetch user information from Google.',
  GOOGLE_ACCESS_VERIFIED: 'Successfully verify Google access token.',
  USER_NOT_FOUND: 'User not found.',
  USER_WAS_UPDATED: 'User was updated.',
  USER_CART_IN_PAYLOAD: 'User cart in payload.',
  CONSUMER_CART_EMPTY: 'Consumer cart is empty.',
  CART_CLEARED_SUCCESSFULLY: 'Cart is successfully cleared.',
  INSUFFICIENT_STOCK: 'Insufficient stock.',
  PRODUCT_UPDATED_IN_CART: 'Product was successfully updated in cart.',
  PRODUCT_REMOVED_FROM_CART: 'Product was successfully removed from cart.',
  WISHLIST_RETRIEVED: 'Список бажань успішно отримано',
  ERROR_GETTING_WISHLIST: 'Помилка отримання списку бажань',
  PRODUCT_ALREADY_IN_WISHLIST: 'Товар вже є у списку бажань',
  PRODUCT_ADDED_TO_WISHLIST: 'Товар успішно додано до списку бажань',
  PRODUCT_NOT_IN_WISHLIST: 'Товар не знайдено у списку бажань',
  ERROR_ADDING_TO_WISHLIST: 'Помилка додавання до списку бажань',
  PRODUCT_REMOVED_FROM_WISHLIST: 'Товар успішно видалено зі списку бажань',
  ERROR_REMOVING_FROM_WISHLIST: 'Помилка видалення зі списку бажань',
  CANNOT_DELETE_ADMIN: 'Cannot detete admin.',
  INVALID_INPUT_DATA: 'Invalid input data.',
  ERROR_UPLOADING_FILE: 'Error uploading file to GCS.',
  ERROR_HANDLING_FILE_UPLOAD: 'Error handling file upload.',
  FILE_SAVED_ON_GCS: 'File saved on Google Cloud Storage.',
  REVIEW_ADDED_SUCCESSFULLY: 'Review added successfully.',
  REVIEWS_RETRIEVED_SUCCESSFULLY: 'Reviews retrieved successfully.',
  REVIEW_UPDATED_SUCCESSFULLY: 'Review updated successfully.',
  REVIEW_DELETED_SUCCESSFULLY: 'Review deleted successfully.',
  REVIEW_NOT_FOUND: 'Review not found.',
  UNAUTHORIZED_TO_UPDATE_REVIEW: 'Unauthorized to update this review.',
  UNAUTHORIZED_TO_DELETE_REVIEW: 'Unauthorized to delete this review.',
  ERROR_WHILE_ADDING_REVIEW: 'Error while adding review.',
  ERROR_WHILE_RETRIEVING_REVIEWS: 'Error while retrieving reviews.',
  ERROR_WHILE_UPDATING_REVIEW: 'Error while updating review.',
  ERROR_WHILE_DELETING_REVIEW: 'Error while deleting review.',
  INTERNAL_SERVER_ERROR: 'Internal Server Error.',
};

export {
  HTTP_STATUS_CODES,
  MESSAGES
};
